// Tous les DTOs sont définis dans @pa-sap-bridge/shared — source unique de vérité.
export type {
  InvoiceStatus,
  InvoiceDirection,
  FileKind,
  InvoiceSummary,
  InvoiceLine,
  InvoiceFile,
  InvoiceDetail,
  SupplierExtracted,
  AuditAction,
  AuditOutcome,
  AuditEntry,
  PaginatedResult,
  AuthUser,
  BasicSettings,
  SapExecutionPolicy,
  SapValidationIssue,
  SapValidationReport,
  SapPurchaseInvoiceRef,
  LinkSapResult,
  LinkSapConflict,
} from '@pa-sap-bridge/shared';
